language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 0053a/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 0053a/docker-react npm run test -- --coverage
